### ISSUE TITLE
UseHttpClient overrides provided digest auth

### ISSUE THREAD

**Issue by n0nick** [mongodb/atlas-sdk-go#303]
**Describe the bug**

When using `UseHttpClient` to provide a custom HTTP client, the authentication config passed through `UseDigestAuth` gets overridden, because auth is stored as a transport on the existing HTTP client.

```go
client, err := admin.NewClient(admin.UseDigestAuth(pubKey, privKey),
	admin.UseHTTPClient(retryClient.StandardClient()))
```

This results in auth failures eventually (`HTTP 401 Unauthorized`) because the digest information is essentially [overridden by UseHttpClient](https://github.com/mongodb/atlas-sdk-go/blob/88da2e5d0ee1ee74d636488e03c0e60a1a0c019f/admin/atlas_client.go#L47-L67).

I didn't test, but I suspect the other direction would also fail - i.e. `NewClient(UseHttpClient, UseDigestAuth)` would just replace the provided HTTP client with a new one that's [created in `UseDigestAuth`](https://github.com/mongodb/atlas-sdk-go/blob/88da2e5d0ee1ee74d636488e03c0e60a1a0c019f/admin/atlas_client.go#L50).

**Expected behavior**

Ideally, I should be able to call both `UseHttpClient` and `UseDigestAuth`, and they'll interact with each other.

Or, document that the two features are exclusive, and how to provide auth if using a custom HTTP client.

**Comment by wtrocki** [comment]
Hi @n0nick 

If you looking for the example on how to make existing digest authentication work with your own transport see:
https://github.com/mongodb/atlas-sdk-go/blob/main/examples/retry/retry.go

We have added this recently and it will cover having custom transport with digest authentication included.

> This results in auth failures eventually (HTTP 401 Unauthorized) because the digest information is essentially [overridden by UseHttpClient](https://github.com/mongodb/atlas-sdk-go/blob/88da2e5d0ee1ee74d636488e03c0e60a1a0c019f/admin/atlas_client.go#L47-L67).

This is in fact an desired behaviour that is missing proper documentation.

> Ideally, I should be able to call both UseHttpClient and UseDigestAuth, and they'll interact with each other.

Sadly golang does not allow to create and use 2 HTTP clients in composable way so we are limited by the platform. 

> Or, document that the two features are exclusive, and how to provide auth if using a custom HTTP client.

We will document that feature as well as provide example to https://github.com/mongodb/atlas-sdk-go/blob/main/examples/retry/retry.go as workaround.

**Comment by n0nick** [comment]
Thanks @wtrocki for the reference, this is actually exactly what I'm working on - adding retry logic via hashicorp/go-retryablehttp 😄 

And ack re documentation as a workaround. I tried thinking of a suggestion on how to compose this elegantly, but the http.Client interface is tricky in that sense.
